# Generated by Django 4.1.4 on 2022-12-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_pan',
            field=models.FileField(blank=True, upload_to='emp_pan/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_voter',
            field=models.FileField(blank=True, upload_to='emp_voter/'),
        ),
    ]
